### ISSUE TITLE
java.lang.IllegalStateException при билде виджета

### ISSUE THREAD

**Issue by k0lourful** [Unact/yandex_mapkit#151]
Появляется на андроид 11, устройство и эмуль с Google APIs образом; на ios не тестировали. Началось после перехода с другого api для карт (использую последнюю гит версию для функционала маршрутизации), причём следовал всем шагам по установке. Происходит во всех местах вызова YandexMap.
Но ещё я поставил гит версию в другом проекте вместо 1.1.1, там такой проблемы нет.

Что делал: `flutter clean`, `flutter pub cache clean`.

Какие-то источники подсказывают, что это может возникать из-за конфликта пакетов, использующих PlatformViews одновременно (в подробности не вдавался). Есть ли другие идеи?
<details><summary>Логи</summary>

  ```
  E/flutter (18994): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: yandex_mapkit/yandex_map
  E/flutter (18994): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:197)
  E/flutter (18994): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
  E/flutter (18994): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
  E/flutter (18994): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
  E/flutter (18994): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
  E/flutter (18994): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
  E/flutter (18994): 	at android.os.MessageQueue.nativePollOnce(Native Method)
  E/flutter (18994): 	at android.os.MessageQueue.next(MessageQueue.java:335)
  E/flutter (18994): 	at android.os.Looper.loop(Looper.java:183)
  E/flutter (18994): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
  E/flutter (18994): 	at java.lang.reflect.Method.invoke(Native Method)
  E/flutter (18994): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  E/flutter (18994): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  E/flutter (18994): , null, null)
  E/flutter (18994): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
  E/flutter (18994): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
  E/flutter (18994): <asynchronous suspension>
  E/flutter (18994): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1066:18)
  E/flutter (18994): <asynchronous suspension>
  E/flutter (18994): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:771:5)
  E/flutter (18994): <asynchronous suspension>
  E/flutter (18994): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
  E/flutter (18994): <asynchronous suspension>
  E/flutter (18994): 
  ```
</details>
<details><summary>Доктор</summary>

```
  [√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1237], locale en-GB)
      • Flutter version 2.5.2 at *****\flutter
      • Upstream repository https://github.com/flutter/flutter.git
      • Framework revision 3595343e20 (8 days ago), 2021-09-30 12:58:18 -0700
      • Engine revision 6ac856380f
      • Dart version 2.14.3
  
  [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
      • Android SDK at *****\AppData\Local\Android\sdk
      • Platform android-31, build-tools 31.0.0
      • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
      • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
      • All Android licenses accepted.
  
  [X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
      ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
  
  [√] Android Studio (version 2020.3)
      • Android Studio at C:\Program Files\Android\Android Studio
      • Flutter plugin can be installed from:
         https://plugins.jetbrains.com/plugin/9212-flutter
      • Dart plugin can be installed from:
         https://plugins.jetbrains.com/plugin/6351-dart
      • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
  
  [√] Connected device (1 available)
      • Edge (web) • edge • web-javascript • Microsoft Edge 94.0.992.38
```
</details>

**Comment by DCrow** [comment]
Подскажите, у вас есть в AndroidManifest.xml такая строка?
```xml
<meta-data
                android:name="flutterEmbedding"
                android:value="2" />
```

**Comment by k0lourful** [comment]
Прошу помочь по этому же вопросу. Решено, что пакет [audio-service](https://pub.dev/packages/audio_service) нужно оставить, но после его установки я не могу использовать mapkit. В доках написано, что нужно переименовать главный activity в манифест-файле. На стэке по этому вопросу сказали, что имя этого activity должен совпадать и в kotlin (или java) файле, но я не знаю как тогда он должен называться. И что именно - просто имя класса, или файла кода, или обоих?

Или же надо создать кастомный activity? А как это сделать я никак не пойму. Если есть решение, я бы любезно попросил пример. Сейчас мой kotlin файл ничем не примечателен:

```kotlin
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import com.yandex.mapkit.MapKitFactory

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MapKitFactory.setApiKey("my_key")
        super.configureFlutterEngine(flutterEngine)
    }
}
```
И в манифесте следующее изменение:
```xml
<activity
    android:name="com.ryanheise.audioservice.AudioServiceActivity"
    <!-- и прочие вещи-->
</activity>
<!-- другие activity, сервисы, разрешения и т.д.-->
```

**Comment by k0lourful** [comment]
Сделал другой пример: перегрузить provideFlutterEngine, чтобы вернуть соответствующий engine из AudioServicePlugin. Это написано в доках по пакету для кастомных activity.
```kotlin
import android.content.Context
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import com.yandex.mapkit.MapKitFactory
import com.ryanheise.audioservice.AudioServicePlugin

class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MapKitFactory.setApiKey("9b598cce-8311-4ae5-8fc5-b536013023f2")
        super.configureFlutterEngine(flutterEngine)
    }

    override fun provideFlutterEngine(context: Context): FlutterEngine? = AudioServicePlugin.getFlutterEngine(context)
}
```
А в манифесте имя activity вернул MainActivity. Опять же, возникает ошибка регистрации типа yandex_mapkit.

**Comment by DCrow** [comment]
Там надо вот так это делать, и кроме этого надо AndroidManifest.xml `android:name` вернуть старое название `.MainActivity`
```java
import android.content.Context
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import com.yandex.mapkit.MapKitFactory
import com.ryanheise.audioservice.AudioServicePlugin

class MainActivity: FlutterActivity() {
  override fun provideFlutterEngine(@NonNull context: Context): FlutterEngine {
    MapKitFactory.setApiKey("YOUR_API_KEY")
    return AudioServicePlugin.getFlutterEngine(context)
  }
}
```

**Comment by k0lourful** [comment]
О боги... оно работает! А мы думали над этим месяц, если не больше! Превеликая благодарность!
