### ISSUE TITLE
Ошибка на Android при получении result от searchByText

### ISSUE THREAD

**Issue by Rogue85** [Unact/yandex_mapkit#160]
Сразу оговорюсь, что на iOS все работает. Проблема встречается только на Android. 

pubspec.yaml
```
  yandex_mapkit:
    git:
      url: git://github.com/Unact/yandex_mapkit
      ref: 01ef7aeac3d9e5c26a783d43690f715737da22ab
```

Вызываю searchByText

```
var geoResult = YandexSearch.searchByText(
        searchText: query,
        geometry: Geometry.fromBoundingBox(BoundingBox(
          southWest: Point(
              latitude: 56.149797, longitude: 36.839596),
          northEast: Point(
              latitude: 55.349066, longitude: 38.307925),
        )),
        searchOptions: SearchOptions(
          searchType: SearchType.geo,
          geometry: false,
        ),
      );

      SearchSessionResult sessionGeoResult = await geoResult.result; // тут ошибка
```

После вызова данного кода получаю следующую ошибку

```
E/MethodChannel#yandex_mapkit/yandex_search( 4812): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at com.unact.yandexmapkit.YandexSearch.searchByText(YandexSearch.java:64)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at com.unact.yandexmapkit.YandexSearch.onMethodCall(YandexSearch.java:42)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#yandex_mapkit/yandex_search( 4812): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 4812): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/flutter ( 4812): 	at com.unact.yandexmapkit.YandexSearch.searchByText(YandexSearch.java:64)
E/flutter ( 4812): 	at com.unact.yandexmapkit.YandexSearch.onMethodCall(YandexSearch.java:42)
E/flutter ( 4812): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 4812): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter ( 4812): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter ( 4812): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 4812): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 4812): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 4812): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 4812): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4812): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 4812): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 4812): )

E/flutter ( 4812): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter ( 4812): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter ( 4812): <asynchronous suspension>
E/flutter ( 4812): #2      SelectAddressScreenState.search
package:app/screens/select_address.dart:94
E/flutter ( 4812): <asynchronous suspension>
E/flutter ( 4812):
```

**Comment by DCrow** [comment]
Здравствуйте!

Да, действительно выдается такая ошибка. 
В мастере поправил.
