### ISSUE TITLE
Ошибка при попытке задать PlacemarkIconStyle(image: null)

### ISSUE THREAD

**Issue by Ae-Mc** [Unact/yandex_mapkit#196]
При попытке задать `PlacemarkIconStyle.image` равным null получаем ошибку:
```
E/flutter ( 5496): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexPlacemarkController.getIconImage(YandexPlacemarkController.java:141)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexPlacemarkController.setIcon(YandexPlacemarkController.java:122)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexPlacemarkController.update(YandexPlacemarkController.java:91)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexPlacemarkController.<init>(YandexPlacemarkController.java:62)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexClusterizedPlacemarkCollectionController.addPlacemark(YandexClusterizedPlacemarkCollectionController.java:101)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexClusterizedPlacemarkCollectionController.addPlacemarks(YandexClusterizedPlacemarkCollectionController.java:84)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexClusterizedPlacemarkCollectionController.updatePlacemarks(YandexClusterizedPlacemarkCollectionController.java:77)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexClusterizedPlacemarkCollectionController.update(YandexClusterizedPlacemarkCollectionController.java:56)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexClusterizedPlacemarkCollectionController.<init>(YandexClusterizedPlacemarkCollectionController.java:51)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexMapObjectCollectionController.addClusterizedPlacemarkCollection(YandexMapObjectCollectionController.java:346)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexMapObjectCollectionController.addMapObjects(YandexMapObjectCollectionController.java:116)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexMapObjectCollectionController.updateMapObjects(YandexMapObjectCollectionController.java:91)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexMapObjectCollectionController.update(YandexMapObjectCollectionController.java:61)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexMapController.applyMapObjects(YandexMapController.java:491)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexMapController.<init>(YandexMapController.java:107)
E/flutter ( 5496): 	at com.unact.yandexmapkit.YandexMapFactory.create(YandexMapFactory.java:25)
E/flutter ( 5496): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:152)
E/flutter ( 5496): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter ( 5496): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 5496): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 5496): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter ( 5496): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
E/flutter ( 5496): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/flutter ( 5496): 	at android.os.Handler.handleCallback(Handler.java:751)
E/flutter ( 5496): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter ( 5496): 	at android.os.Looper.loop(Looper.java:154)
E/flutter ( 5496): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/flutter ( 5496): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5496): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/flutter ( 5496): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/flutter ( 5496): )
```

**Comment by DCrow** [comment]
`PlacemarkIconStyle.image` должен быть nullable, то что выдается ошибка бага.

**Comment by DCrow** [comment]
Все же ошибся в предыдущем комментарии. 
Запретил image делать nullable. 
В случае если не хочется указывать image, надо указывать icon целиком null.
