### ISSUE TITLE
Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: yandex_mapkit/yandex_map

### ISSUE THREAD

**Issue by NabilaAwad** [Unact/yandex_mapkit#230]
I have this problem and i couldn't find answer . when i run the project it give me this error below and the output always white screen 
the error is :`E/flutter (17799): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: yandex_mapkit/yandex_map
E/flutter (17799): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:189)
E/flutter (17799): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (17799): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (17799): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (17799): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (17799): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter (17799): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
E/flutter (17799): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (17799): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (17799): 	at android.os.Looper.loop(Looper.java:246)
E/flutter (17799): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/flutter (17799): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (17799): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (17799): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (17799): , null, null)
E/flutter (17799): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:628:7)
E/flutter (17799): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (17799): <asynchronous suspension>
E/flutter (17799): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1107:18)
E/flutter (17799): <asynchronous suspension>
E/flutter (17799): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:762:5)
E/flutter (17799): <asynchronous suspension>
E/flutter (17799): 
I/ViewRootImpl@2823d7d[MainActivity](17799): ViewPostIme key 0
I/ViewRootImpl@2823d7d[MainActivity](17799): ViewPostIme key 1
I/ViewRootImpl@2823d7d[MainActivity](17799): MSG_WINDOW_FOCUS_CHANGED 0 1
I/SurfaceControl(17799): nativeRelease nativeObject s[537738896192]
I/SurfaceControl(17799): nativeRelease nativeObject e[537738896192]
I/SurfaceControl(17799): nativeRelease nativeObject s[539362534624]
I/SurfaceControl(17799): nativeRelease nativeObject e[539362534624]
I/SurfaceControl(17799): nativeRelease nativeObject s[539362534432]
I/SurfaceControl(17799): nativeRelease nativeObject e[539362534432]
D/InputTransport(17799): Input channel destroyed: 'ClientS', fd=104
I/SurfaceControl(17799): nativeRelease nativeObject s[537738896288]
I/SurfaceControl(17799): nativeRelease nativeObject e[537738896288]
I/SurfaceView(17799): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{15ab121 V.E...... ........ 0,0-720,1516} of ViewRootImpl@2823d7d[MainActivity]
I/SurfaceView(17799): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{15ab121 V.E...... ........ 0,0-720,1516}
W/libEGL  (17799): EGLNativeWindowType 0x7bf4d68010 disconnect failed
I/SurfaceView(17799): remove() from RT android.view.SurfaceView$2@da74b2a Surface(name=SurfaceView - com.example.untitled16/com.example.untitled16.MainActivity@15ab121@0)/@0x354a034
I/SurfaceControl(17799): nativeRelease nativeObject s[532386312992]
I/SurfaceControl(17799): nativeRelease nativeObject e[532386312992]
I/SurfaceControl(17799): nativeRelease nativeObject s[532386312896]
I/SurfaceControl(17799): nativeRelease nativeObject e[532386312896]
W/libEGL  (17799): EGLNativeWindowType 0x7bf4d66010 disconnect failed
I/SurfaceControl(17799): nativeRelease nativeObject s[532386316928]
I/SurfaceControl(17799): nativeRelease nativeObject e[532386316928]
I/SurfaceControl(17799): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x5452eb8 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1810 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/SurfaceControl(17799): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x61ba946 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/SurfaceControl(17799): nativeRelease nativeObject s[532386312800]
I/SurfaceControl(17799): nativeRelease nativeObject e[532386312800]
I/ViewRootImpl@2823d7d[MainActivity](17799): Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)8 dur=11 res=0x5 s={false 0} ch=true fn=33
I/SurfaceView(17799): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{15ab121 V.E...... ........ 0,0-720,1516} of ViewRootImpl@2823d7d[MainActivity]
I/ViewRootImpl@2823d7d[MainActivity](17799): stopped(true) old=false
D/AndroidRuntime(17799): Shutting down VM
E/AndroidRuntime(17799): FATAL EXCEPTION: main
E/AndroidRuntime(17799): Process: com.example.untitled16, PID: 17799
E/AndroidRuntime(17799): java.lang.RuntimeException: Unable to destroy activity {com.example.untitled16/com.example.untitled16.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
E/AndroidRuntime(17799): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5675)
E/AndroidRuntime(17799): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5720)
E/AndroidRuntime(17799): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
E/AndroidRuntime(17799): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(17799): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(17799): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
E/AndroidRuntime(17799): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17799): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(17799): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/AndroidRuntime(17799): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17799): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(17799): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(17799): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
E/AndroidRuntime(17799): 	at com.unact.yandexmapkit.YandexMapkitPlugin.teardownChannels(YandexMapkitPlugin.java:60)
E/AndroidRuntime(17799): 	at com.unact.yandexmapkit.YandexMapkitPlugin.onDetachedFromEngine(YandexMapkitPlugin.java:41)
E/AndroidRuntime(17799): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime(17799): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
E/AndroidRuntime(17799): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
E/AndroidRuntime(17799): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
E/AndroidRuntime(17799): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:422)
E/AndroidRuntime(17799): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:699)
E/AndroidRuntime(17799): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
E/AndroidRuntime(17799): 	at android.app.Activity.performDestroy(Activity.java:8468)
E/AndroidRuntime(17799): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
E/AndroidRuntime(17799): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5660)
E/AndroidRuntime(17799): 	... 11 more
I/Process (17799): Sending signal. PID: 17799 SIG: 9`

flutter doctor -v:
`[√] Flutter (Channel master, 3.1.0-0.0.pre.729, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
    • Flutter version 3.1.0-0.0.pre.729 at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e01522c83e (2 days ago), 2022-05-16 04:49:06 -0400
    • Engine revision c40bc1313c
    • Dart version 2.18.0 (build 2.18.0-116.0.dev)
    • DevTools version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\dc\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\dc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A217F (mobile) • RF8R5184E4W • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 100.0.1185.36

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`
Android Manifest:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.untitled16">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
   <application
        android:label="untitled16"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`
I have did flutter clean more than one and uninstall app and use different emulator, the error is same

**Comment by DCrow** [comment]
Hello!

Most likely some of your dependencies are changing the way how plugins are initialized.
Can you please add your `pubspec.yaml`?

**Comment by NabilaAwad** [comment]
Hi, ok this is :
name: untitled16
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  yandex_mapkit: ^2.0.5



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by NabilaAwad** [comment]
Hi, ok this is : 
`name: untitled16
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  yandex_mapkit: ^2.0.5



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by DCrow** [comment]
Did you do everything specified [here](https://github.com/Unact/yandex_mapkit#initializing-for-android)?

**Comment by NabilaAwad** [comment]
yes , every thing

**Comment by DCrow** [comment]
Is it possible to include your example app?

As of now I don't see any problem except that your app is somehow misconfigured.

**Comment by NabilaAwad** [comment]
yes, but sorry it will take a time because the internet is so bad in my region

**Comment by DCrow** [comment]
For some reason flutter masks the real error message which is 
```
E/GeneratedPluginRegistrant: Error registering plugin yandex_mapkit, com.unact.yandexmapkit.YandexMapkitPlugin
    java.lang.RuntimeException: Locale parameter is incorrect: divider is missing or not '_'
```

This means that you have specified a wrong locale in `MainActivity.kt`. 
Since there is no "en" locale, you need to also indicate the region like this "en_US".

Unfortunately all available languages are not documented, so it is impossible to know which ones are supported.

**Comment by UkioMaeni** [comment]
> For some reason flutter masks the real error message which is
> 
> ```
> E/GeneratedPluginRegistrant: Error registering plugin yandex_mapkit, com.unact.yandexmapkit.YandexMapkitPlugin
>     java.lang.RuntimeException: Locale parameter is incorrect: divider is missing or not '_'
> ```
> 
> This means that you have specified a wrong locale in `MainActivity.kt`. Since there is no "en" locale, you need to also indicate the region like this "en_US".
> 
> Unfortunately all available languages are not documented, so it is impossible to know which ones are supported.

How did you get the real error? I have an error like the author of the topic and nothing helps, even changing the locale.
