### ISSUE TITLE
Ошибка YandexSearch

### ISSUE THREAD

**Issue by dumptyhumpty2014gmail** [Unact/yandex_mapkit#275]
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yandex/mapkit/search/SearchFactory;
       at com.unact.yandexmapkit.YandexSearch.<init>(YandexSearch.java:28)
       at com.unact.yandexmapkit.YandexMapkitPlugin.setupChannels(YandexMapkitPlugin.java:48)
       at com.unact.yandexmapkit.YandexMapkitPlugin.onAttachedToEngine(YandexMapkitPlugin.java:38)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:79)
       at ru.goldapple.courier.MainActivity.configureFlutterEngine(MainActivity.java:50)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
       at android.app.Activity.performCreate(Activity.java:7802)
       at android.app.Activity.performCreate(Activity.java:7791)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
Поиски, расчеты маршрута и прочее не используется. Только вывод карты, маркеры и кластеры. На дебаг сборке не воспроизводится пока.

**Comment by dumptyhumpty2014gmail** [comment]
Caused by java.lang.ClassNotFoundException: Didn't find class "com.yandex.mapkit.search.SearchFactory" on path: DexPathList[[zip file "/data/app/--vLO0amuB0hyVXDB80RUcg==/base.apk"],nativeLibraryDirectories=[/data/app/--vLO0amuB0hyVXDB80RUcg==/lib/x86, /data/app/--vLO0amuB0hyVXDB80RUcg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.unact.yandexmapkit.YandexSearch.<init>(YandexSearch.java:28)
       at com.unact.yandexmapkit.YandexMapkitPlugin.setupChannels(YandexMapkitPlugin.java:48)
       at com.unact.yandexmapkit.YandexMapkitPlugin.onAttachedToEngine(YandexMapkitPlugin.java:38)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:79)
       at                      .MainActivity.configureFlutterEngine(MainActivity.java:50)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
       at android.app.Activity.performCreate(Activity.java:7802)
       at android.app.Activity.performCreate(Activity.java:7791)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by DCrow** [comment]
Здравствуйте!

Подскажите, вы точно сделали все как описано в https://github.com/Unact/yandex_mapkit#initializing-for-android ?
Не использовали com.yandex.android:maps.mobile:4.2.0-lite ?
