### ISSUE TITLE
CRASH on flutter 3.7.1

### ISSUE THREAD

**Issue by DmitriySimonov** [Unact/yandex_mapkit#301]
An error occurs when launching the map screen

FATAL EXCEPTION: main
                 Process: com.., PID: 27282
                 java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/com...-eUunlxEWrjDjD3zDTZ15Cw==/base.apk)
                 	at com.yandex.runtime.sensors.internal.FusedLocationSubscription.onConnected(FusedLocationSubscription.java:71)
                 	at com.google.android.gms.common.internal.zak.zad(com.google.android.gms:play-services-base@@18.1.0:11)
                 	at com.google.android.gms.common.api.internal.zabe.zab(com.google.android.gms:play-services-base@@18.1.0:3)
                 	at com.google.android.gms.common.api.internal.zaaw.zaC(com.google.android.gms:play-services-base@@18.1.0:11)
                 	at com.google.android.gms.common.api.internal.zaaw.zag(com.google.android.gms:play-services-base@@18.1.0:4)
                 	at com.google.android.gms.common.api.internal.zabi.onConnected(com.google.android.gms:play-services-base@@18.1.0:2)
                 	at com.google.android.gms.common.api.internal.zat.onConnected(com.google.android.gms:play-services-base@@18.1.0:1)
                 	at com.google.android.gms.common.internal.zah.onConnected(com.google.android.gms:play-services-base@@18.1.0:1)
                 	at com.google.android.gms.common.internal.zzf.zzd(com.google.android.gms:play-services-basement@@18.1.0:10)
                 	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:4)
                 	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
                 	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
                 	at android.os.Handler.dispatchMessage(Handler.java:107)
                 	at android.os.Looper.loop(Looper.java:214)
                 	at android.app.ActivityThread.main(ActivityThread.java:7356)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by berdibekovaG** [comment]
the same trouble at flutter 3.7.5

D/AndroidRuntime(11266): Shutting down VM
E/AndroidRuntime(11266): FATAL EXCEPTION: main
E/AndroidRuntime(11266): Process: kz.magnum.driver.android, PID: 11266
E/AndroidRuntime(11266): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~KQRIqGTYNKL-HpL3rAIpTg==/kz.magnum.driver.android-I66GBzusMmDSlnOB1rRF1w==/base.apk)
E/AndroidRuntime(11266): 	at com.yandex.runtime.sensors.internal.FusedLocationSubscription.onConnected(FusedLocationSubscription.java:71)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.internal.zak.zad(com.google.android.gms:play-services-base@@18.1.0:11)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.api.internal.zabe.zab(com.google.android.gms:play-services-base@@18.1.0:3)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.api.internal.zaaw.zaC(com.google.android.gms:play-services-base@@18.1.0:11)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.api.internal.zaaw.zag(com.google.android.gms:play-services-base@@18.1.0:4)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.api.internal.zabi.onConnected(com.google.android.gms:play-services-base@@18.1.0:2)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.api.internal.zat.onConnected(com.google.android.gms:play-services-base@@18.1.0:1)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.internal.zah.onConnected(com.google.android.gms:play-services-base@@18.1.0:1)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.internal.zzf.zzd(com.google.android.gms:play-services-basement@@18.1.0:10)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:4)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
E/AndroidRuntime(11266): 	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
E/AndroidRuntime(11266): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11266): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(11266): 	at android.app.ActivityThread.main(ActivityThread.java:8037)
E/AndroidRuntime(11266): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11266): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(11266): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
I/TRuntime.CctTransportBackend(11266): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TRuntime.CctTransportBackend(11266): Status Code: 200
I/Process (11266): Sending signal. PID: 11266 SIG: 9
Lost connection to device.

**Comment by Likhachev17** [comment]
same trouble 3.7.1

**Comment by pamir72** [comment]
I have the same problem. But I also use geolocator package. Now I solved this problem not updating geolocator_android to version 4.1.7. I left 4.1.4.

**Comment by AlexSeednov** [comment]
3.7.3 same

@pamir72 your solution works awesome! Thanks for saved time

**Comment by Legendorik** [comment]
The problem here is that Yandex maps depend on "com.google.android.gms:play-services-location:20.0.0", while more up-to-date geolocation packages depend on "com.google.android.gms:play-services-location:21.0.0". In case you cannot downgrade a dependency, you can try to configure version resolution in android/build.gradle
```
allprojects {
    repositories {
        google()
        mavenCentral()
        // Add this line
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-location:20.0.0"
            }
        }
    }
}
```

**Comment by DCrow** [comment]
Hello!

Can you reproduce this bug with the latest library version?

**Comment by pamir72** [comment]
Confirm! With latest version (3.3.0) problem has disappeared. Thank you!
