### ISSUE TITLE
Краш при вызове метода moveCamera на Android

### ISSUE THREAD

**Issue by egortabula** [Unact/yandex_mapkit#350]
Приветствую!
Я использую версию пакета 3.4.0

Код который я вызываю:
```
void moveCameraToRoute() async {
    final route = objects.firstWhere(
      (el) => el.mapId == routeLine,
    ) as PolylineMapObject?;

    try {
      await mapController.moveCamera(
        CameraUpdate.newGeometry(
          Geometry.fromPolyline(route!.polyline),
        ),
        animation: const MapAnimation(
          type: MapAnimationType.smooth,
        ),
      );
      await mapController.moveCamera(CameraUpdate.zoomOut());
    } catch (e) {
      debugPrint(e.toString());
    }
  }
```

При вызове метода на ios все работает, но на android я ловлю PlatformException
 
` PlatformException (PlatformException(error, Invalid variant value
at com.yandex.mapkit.map.internal.MapBinding.cameraPosition(Native Method)
	at com.unact.yandexmapkit.YandexMapController.newGeometry(YandexMapController.java:442)
	at com.unact.yandexmapkit.YandexMapController.cameraUpdateToPosition(YandexMapController.java:405)
	at com.unact.yandexmapkit.YandexMapController.moveCamera(YandexMapController.java:337)
	at com.unact.yandexmapkit.YandexMapController.onMethodCall(YandexMapController.java:157)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
`

**Comment by DCrow** [comment]
Здравствуйте!

Поправил в мастере. В ближайшее время на pub.dev будет отдельная версия.

**Comment by egortabula** [comment]
> Здравствуйте!
> 
> Поправил в мастере. В ближайшее время на pub.dev будет отдельная версия.

Здравствуйте, спасибо большое!
