### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified

### ISSUE THREAD

**Issue by VladVKozlov** [Unact/yandex_mapkit#372]
Ошибка при старте андроид приложения в дебаг версии в эмуляторе

flutter: yandex_mapkit v4.0.2
native mapkit: "com.yandex.android:maps.mobile:4.5.1-lite"

targetSdkVersion 34
compileSdkVersion 34
minSdkVersion 28

Пробовал использовать более новую версию native mapkit: "com.yandex.android:maps.mobile:4.6.1-lite", та же ошибка

Эта же проблема в [mapkit demo repo](https://github.com/yandex/mapkit-android-demo/issues/359)

StackTrace:
```
Debug service listening on ws://127.0.0.1:62432/Ykiu9Lwev-A=/ws
Syncing files to device sdk gphone64 x86 64...
W/OpenGLRenderer(10085): Failed to initialize 101010-2 format, error = EGL_SUCCESS
I/Gralloc4(10085): mapper 4.x is not supported
D/FlutterLocationService(10085): Creating service.
D/FlutterLocationService(10085): Binding to location service.
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): Cannot register receiver
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): java.lang.SecurityException: **<removed>**: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): 	at android.os.Parcel.createException(Parcel.java:3041)
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): 	at android.os.Parcel.readException(Parcel.java:3024)
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): 	at android.os.Parcel.readException(Parcel.java:2966)
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
E/com.yandex.runtime.connectivity.internal.ConnectivitySubscription(10085): 	at android.app.ContextImpl
```

**Comment by Arkuda** [comment]
Same error
