### ISSUE TITLE
MissingPluginException(No implementation found for method initSession on channel yandex mapkit/yandex_search)

### ISSUE THREAD

**Issue by MrErkinjon** [Unact/yandex_mapkit#375]
......pubspec.yaml..........
environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
 yandex_mapkit: ^4.1.0
.......

........ Code ........
 Future<String?> getPlaceMarkFromYandex(Point? position) async {
  SearchSessionResult? resultWithSession;
  if (position != null) {
    resultWithSession = await (await YandexSearch.searchByPoint(point: position, searchOptions: const SearchOptions(searchType: SearchType.none, geometry: false))).$2;
  }
  var address = (resultWithSession)?.items?.first.toponymMetadata?.address.addressComponents.formatAddressYandex();
  return address;
}
............
Error
I/flutter (27604): MissingPluginException(No implementation found for method initSession on channel yandex_mapkit/yandex_search)
I/flutter (27604): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
I/flutter (27604): <asynchronous suspension>
I/flutter (27604): #1      YandexSearch._initSession (package:yandex_mapkit/src/yandex_search.dart:36:5)
I/flutter (27604): <asynchronous suspension>
I/flutter (27604): #2      YandexSearch.searchByPoint (package:yandex_mapkit/src/yandex_search.dart:27:21)
I/flutter (27604): <asynchronous suspension>
I/flutter (27604): #3      getPlaceMarkFromYandex (package:al_mansur_driver/utils/utils.dart:908:32)
I/flutter (27604): <asynchronous suspension>

**Comment by 78Ronin78** [comment]
У меня такая же проблема, только на стороне iOS. С Android все норм(ОК).

**Comment by Nodirbek05** [comment]
Hi there!!

I am having such error could you please give me an instruction what should i add for Podfile
