### ISSUE TITLE
Крэш на Андроиде при вызове FlutterEngine.destroy из фонового сервиса

### ISSUE THREAD

**Issue by alod2019** [Unact/yandex_mapkit#379]
В приложении реализована фоновая обработка событий как описано в [Background processes](https://docs.flutter.dev/packages-and-plugins/background-processes) и в ходе которой создается отдельный FlutterEngine и потом, после обработки события. уничтожается. Проблема в том, что при этом возникает крэш
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void x6.k.e(x6.k$c)' on a null object reference
       at com.unact.yandexmapkit.full.InitFull.teardownChannels(InitFull.java:1)
       at com.unact.yandexmapkit.full.InitFull.onDetachedFromEngine(InitFull.java:1)
       at com.unact.yandexmapkit.YandexMapkitPlugin.onDetachedFromEngine(YandexMapkitPlugin.java:3)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:1)
```
Приложение собрано Flutter 3.19.6

**Comment by alod2019** [comment]
Проблема возникла после обновления с версии 4.0.2 на 4.1.0 и, похоже, из-за того, что YandexMapkitPlugin теперь реализован через синглтон BuildConfig.YANDEX_MAPKIT_INIT, а раньше внутри плагина создавался отдельный инстанс variantInit, было
```
public class YandexMapkitPlugin implements FlutterPlugin, ActivityAware {
  private final Init variantInit;

  public YandexMapkitPlugin() throws IllegalAccessException, InstantiationException {
    this.variantInit = (Init) BuildConfig.YANDEX_MAPKIT_INIT_CLASS.newInstance();
  }

  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding binding) {
    variantInit.onAttachedToEngine(binding);
  }

```
стало
```
public class YandexMapkitPlugin implements FlutterPlugin, ActivityAware {

  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding binding) {
    BuildConfig.YANDEX_MAPKIT_INIT.onAttachedToEngine(binding);
  }

```

**Comment by kasperdun** [comment]
Проблема будет как-то решаться или есть workaround?

**Comment by DCrow** [comment]
Исправлено в PR #414
