### ISSUE TITLE
PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: yandex_mapkit/yandex_map

### ISSUE THREAD

**Issue by sunnat-jon** [Unact/yandex_mapkit#387]
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: yandex_mapkit/yandex_map
	at io.flutter.plugin.platform.x.M(Unknown Source:94)
	at io.flutter.plugin.platform.x$a.d(Unknown Source:15)
	at e8.m$a.c(Unknown Source:122)
	at e8.m$a.onMethodCall(Unknown Source:175)
	at f8.k$a.a(Unknown Source:17)
	at t7.c.l(Unknown Source:18)
	at t7.c.m(Unknown Source:41)
	at t7.c.i(Unknown Source:0)
	at t7.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
, null, null). Error thrown main.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:648)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at ExpensiveAndroidViewController._sendCreateMessage(platform_views.dart:1099)
       at AndroidViewController.create(platform_views.dart:822)
        
        
[✓] Flutter (Channel stable, 3.19.6, on macOS 15.1.1 24B91 darwin-arm64, locale en-GB)
    • Flutter version 3.19.6 on channel stable at /Users/khusvr/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (8 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/khusvr/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 15.1.1 24B91 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by kapold** [comment]
i have the same issue, did you fix it?

**Comment by kapold** [comment]
Read this docs (https://pub.dev/packages/yandex_mapkit) and check if all conditions done. For example, i forgot to change MainActivity to MainApplication in AndroidManifest. I think your app dont have access to API key.

 <application
        android:label=...
        android:name=".MainApplication"
        android:icon=...>

**Comment by selawik** [comment]
Same issue. Any updates?
