### ISSUE TITLE
Do not run on Android

### ISSUE THREAD

**Issue by bukenov** [Unact/yandex_mapkit#63]
java.lang.UnsatisfiedLinkError: Couldn't load c++_shared
 	at com.yandex.runtime.Runtime.loadLibrary(Runtime.java:124)
 	at com.yandex.runtime.Runtime.init(Runtime.java:99)
 	at com.yandex.mapkit.MapKitFactory.initialize(MapKitFactory.java:25)
 	at com.yandex.mapkit.search.SearchFactory.initialize(SearchFactory.java:14)
 	at com.unact.yandexmapkit.YandexSearch.<init>(YandexSearch.java:37)
 	at com.unact.yandexmapkit.YandexSearch.registerWith(YandexSearch.java:45)
 	at com.unact.yandexmapkit.YandexMapkitPlugin.registerWith(YandexMapkitPlugin.java:21)
 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
 	at kz.kunde_app.MainActivity.configureFlutterEngine(MainActivity.kt:11)
 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
 	at android.app.Activity.performCreate(Activity.java:7802)
 	at android.app.Activity.performCreate(Activity.java:7791)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
 	at android.os.Handler.dispatchMessage(Handler.java:107)
 	at android.os.Looper.loop(Looper.java:214)
 	at android.app.ActivityThread.main(ActivityThread.java:7397)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by DCrow** [comment]
Hello!

Please provide your `flutter doctor --verbose` and your `pubspec.yaml`

**Comment by DCrow** [comment]
Closing since previous question has not been answered.
